-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS sessions(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  sub BIGINT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  expired_at TIMESTAMP WITH TIME ZONE NOT NULL,
  PRIMARY KEY(id),
  CONSTRAINT sessions_fk_users FOREIGN KEY(sub) REFERENCES users(id)
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS sessions;
-- +goose StatementEnd
